token = "---"
guild_id = 0
guild_error_text = "Current guild couldn't be found, maybe the bot isn't in the right guild or the value in the settings file is incorrect?"

[roles]
lpd = 12345

[patrol_time]
monitored_categories = [23456]
monitored_channels = [34567]
ignored_channels = [45678]
bad_main_channel_starts = ["Dispatch", "At Station", "Training"]
